# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: melangue.com
description: |
  tinkering with (but not limited to) Apple stuff.   
  some assembly required.  
  wonky automation / workflow / scripting & misc

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_repo: jekyll # the GitHub repo name for your project
github_username: jekyll

# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
social_link: twitter
social_username: jekyllrb

# Set theme color here
# Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow.
theme_color: melangue

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Pagination
paginate                     : 4
paginate_path                : '/page-:num/'

# Sass settings
sass:
  sass_dir                : _sass
  style                   : compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
# https://github.com/jekyll/jekyll/issues/4619
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
#  syntax_highlighter_opts:
#    css_class: 'highlight'
#    span:
#      line_numbers: false
#    block:
#      line_numbers: true  

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings               : all
  endings                 : all
  comments                : ["<!-- ", " -->"]
  blanklines              : true
  profile                 : false
  ignore:
  envs                    : [local]


# Added
# - pagination
# - archive page
# - rouge code highlighting
# - one style
# - html compression layout

# Redone
# - using system fonts
# - layout, more centered (borders), smaller h0 headings
# - sass - partials are in style.scss, not themes so it's easier to update them
# - css - added body background variable
# - css - links now have underline on hover, and all of them except nav / pagination / post link headers have link accent color
